services:
  django_avant:
    container_name: django_avant
    restart: unless-stopped
    build:
      context: ./backend
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/audio:/app/audio
    ports:
      - "8015:8000"

  react_avant:
    container_name: react_avant
    build:
      context: ./frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3015:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - django_avant

  nginx:
    container_name: nginx_avant
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    depends_on:
      - django_avant
    volumes:
      - ./nginx/avant.local.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/staticfiles:/app/staticfiles:ro
      - ./backend/audio:/app/audio:ro
    ports:
      - "8085:8085"
